/**
 * Copyright (c) 2026 Sarah Walsh. All rights reserved.
 * Proprietary commercial software published for public reference only.
 * No license is granted to use, copy, modify, distribute, or create derivative works.
 */

/**
 * UNIT TESTS - AI Content Blocker Pro
 * Test individual functions in isolation
 * Run with: node test/unit.test.js
 */

'use strict';

// Test Framework (using simple assertions - no dependencies)
class TestRunner {
  constructor() {
    this.tests = [];
    this.passed = 0;
    this.failed = 0;
  }

  describe(suiteName, fn) {
    console.log(`\n${suiteName}`);
    fn();
  }

  it(testName, fn) {
    try {
      fn();
      this.passed++;
      console.log(`  ✓ ${testName}`);
    } catch (error) {
      this.failed++;
      console.error(`  ✗ ${testName}`);
      console.error(`    ${error.message}`);
    }
  }

  assertEqual(actual, expected, message) {
    if (actual !== expected) {
      throw new Error(`${message || 'Assertion failed'}: expected ${expected}, got ${actual}`);
    }
  }

  assertTrue(value, message) {
    if (value !== true) {
      throw new Error(message || 'Expected true');
    }
  }

  assertFalse(value, message) {
    if (value !== false) {
      throw new Error(message || 'Expected false');
    }
  }

  assertExists(value, message) {
    if (value === null || value === undefined) {
      throw new Error(message || 'Expected value to exist');
    }
  }

  assertThrows(fn, message) {
    try {
      fn();
      throw new Error(message || 'Expected function to throw');
    } catch (e) {
      // Expected
    }
  }

  report() {
    console.log(`\n${'='.repeat(60)}`);
    console.log(`Tests Passed: ${this.passed}`);
    console.log(`Tests Failed: ${this.failed}`);
    console.log(`Total: ${this.passed + this.failed}`);
    console.log(`${'='.repeat(60)}\n`);
    return this.failed === 0;
  }
}

const test = new TestRunner();

// ============================================================================
// UNIT TESTS: calculateKeywordScore
// ============================================================================

test.describe('Unit: calculateKeywordScore()', () => {
  // Mock function (from background.js)
  function calculateKeywordScore(content, terms) {
    try {
      let score = 0;
      const validTerms = Array.isArray(terms) ? terms.filter(t => typeof t === 'string') : [];
      
      validTerms.forEach(term => {
        if (content.includes(term.toLowerCase())) {
          score += 0.3;
        }
      });
      return Math.min(score, 1);
    } catch (e) {
      return 0;
    }
  }

  test.it('returns 0 for empty content', () => {
    const result = calculateKeywordScore('', ['ai-generated']);
    test.assertEqual(result, 0, 'Empty content should score 0');
  });

  test.it('returns 0 for no matched terms', () => {
    const result = calculateKeywordScore('This is normal content', ['ai-generated', 'midjourney']);
    test.assertEqual(result, 0, 'No matches should score 0');
  });

  test.it('returns 0.3 for single match', () => {
    const result = calculateKeywordScore('This was ai-generated', ['ai-generated']);
    test.assertEqual(result, 0.3, 'One match should score 0.3');
  });

  test.it('returns 0.6 for two matches', () => {
    const result = calculateKeywordScore('ai-generated by midjourney', ['ai-generated', 'midjourney']);
    test.assertEqual(result, 0.6, 'Two matches should score 0.6');
  });

  test.it('caps score at 1.0', () => {
    const result = calculateKeywordScore('ai-generated midjourney dalle stable diffusion', 
      ['ai-generated', 'midjourney', 'dalle', 'stable diffusion']);
    test.assertEqual(result, 1, 'Score should cap at 1.0');
  });

  test.it('is case-insensitive', () => {
    const result = calculateKeywordScore('ai-generated', ['AI-GENERATED']);
    test.assertEqual(result, 0.3, 'Should be case-insensitive');
  });

  test.it('handles invalid terms array', () => {
    const result = calculateKeywordScore('ai-generated', null);
    test.assertEqual(result, 0, 'Should handle null terms');
  });

  test.it('filters non-string terms', () => {
    const result = calculateKeywordScore('ai-generated', ['ai-generated', 123, null]);
    test.assertEqual(result, 0.3, 'Should filter non-string terms');
  });
});

// ============================================================================
// UNIT TESTS: validateLicense
// ============================================================================

test.describe('Unit: License Key Validation', () => {
  function isValidLicenseFormat(key) {
    if (!key || typeof key !== 'string') return false;
    return /^AIB-[A-Z0-9]{20}$/.test(key.toUpperCase());
  }

  test.it('rejects null key', () => {
    test.assertFalse(isValidLicenseFormat(null), 'Null should be invalid');
  });

  test.it('rejects empty string', () => {
    test.assertFalse(isValidLicenseFormat(''), 'Empty string should be invalid');
  });

  test.it('rejects invalid prefix', () => {
    test.assertFalse(isValidLicenseFormat('KEY-12345678901234567890'), 'Invalid prefix should be rejected');
  });

  test.it('rejects wrong length', () => {
    test.assertFalse(isValidLicenseFormat('AIB-12345'), 'Too short should be invalid');
  });

  test.it('accepts valid format', () => {
    test.assertTrue(isValidLicenseFormat('AIB-ABCDEFGHIJKLMNOPQRST'), 'Valid format should be accepted');
  });

  test.it('accepts lowercase input', () => {
    test.assertTrue(isValidLicenseFormat('aib-abcdefghijklmnopqrst'), 'Lowercase should be accepted');
  });

  test.it('rejects special characters', () => {
    test.assertFalse(isValidLicenseFormat('AIB-ABC!@#$%^&*()[]{}'), 'Special chars should be rejected');
  });

  test.it('accepts numbers in key', () => {
    test.assertTrue(isValidLicenseFormat('AIB-12345678901234567890'), 'Numbers should be valid');
  });
});

// ============================================================================
// UNIT TESTS: Domain Blocking
// ============================================================================

test.describe('Unit: Domain Blocking/Whitelisting', () => {
  function isDomainBlocked(hostname, blockedDomains) {
    if (!blockedDomains || !Array.isArray(blockedDomains) || blockedDomains.length === 0) {
      return false;
    }
    return blockedDomains.some(blocked => 
      typeof blocked === 'string' && hostname.includes(blocked)
    );
  }

  test.it('returns false for empty blocklist', () => {
    test.assertFalse(isDomainBlocked('example.com', []), 'Empty list should not block');
  });

  test.it('returns false for null blocklist', () => {
    test.assertFalse(isDomainBlocked('example.com', null), 'Null should not block');
  });

  test.it('blocks exact domain match', () => {
    test.assertTrue(isDomainBlocked('evil.com', ['evil.com']), 'Exact match should block');
  });

  test.it('blocks subdomain match', () => {
    test.assertTrue(isDomainBlocked('sub.evil.com', ['evil.com']), 'Subdomain should block');
  });

  test.it('does not block non-matching domain', () => {
    test.assertFalse(isDomainBlocked('good.com', ['evil.com']), 'Non-match should not block');
  });

  test.it('filters non-string entries', () => {
    test.assertFalse(isDomainBlocked('example.com', [null, 123, undefined]), 'Non-strings should be filtered');
  });

  test.it('handles multiple blocked domains', () => {
    test.assertTrue(isDomainBlocked('bad.com', ['evil.com', 'bad.com', 'awful.com']), 'Should match second domain');
  });
});

// ============================================================================
// UNIT TESTS: Trial Period Calculation
// ============================================================================

test.describe('Unit: Trial Period Calculation', () => {
  function calculateTrialDaysRemaining(trialStart) {
    try {
      if (!trialStart || typeof trialStart !== 'number') {
        return 30;
      }
      const elapsed = Date.now() - trialStart;
      const daysElapsed = Math.floor(elapsed / (24 * 60 * 60 * 1000));
      const daysRemaining = Math.max(0, 30 - daysElapsed);
      return daysRemaining;
    } catch (e) {
      return 30;
    }
  }

  test.it('returns 30 for null start date', () => {
    const result = calculateTrialDaysRemaining(null);
    test.assertEqual(result, 30, 'Null should default to 30 days');
  });

  test.it('returns 30 for just installed', () => {
    const result = calculateTrialDaysRemaining(Date.now());
    test.assertEqual(result, 30, 'Just installed should be 30 days');
  });

  test.it('returns ~29 for 1 day old', () => {
    const oneDayAgo = Date.now() - (1 * 24 * 60 * 60 * 1000);
    const result = calculateTrialDaysRemaining(oneDayAgo);
    test.assertEqual(result, 29, 'One day old should be ~29 days');
  });

  test.it('returns 0 for expired trial', () => {
    const thirtyOneDaysAgo = Date.now() - (31 * 24 * 60 * 60 * 1000);
    const result = calculateTrialDaysRemaining(thirtyOneDaysAgo);
    test.assertEqual(result, 0, 'Expired should return 0');
  });

  test.it('never returns negative', () => {
    const hundredDaysAgo = Date.now() - (100 * 24 * 60 * 60 * 1000);
    const result = calculateTrialDaysRemaining(hundredDaysAgo);
    test.assertTrue(result >= 0, 'Should never be negative');
  });
});

// ============================================================================
// UNIT TESTS: Analytics Calculation
// ============================================================================

test.describe('Unit: Analytics Report Generation', () => {
  function generateAnalyticsReport(analytics) {
    const blockRate = analytics.analyzed > 0 
      ? ((analytics.blocked / analytics.analyzed) * 100).toFixed(2)
      : 0;
    
    return {
      totalAnalyzed: analytics.analyzed || 0,
      totalBlocked: analytics.blocked || 0,
      blockRate: `${blockRate}%`,
      sessionDuration: Date.now() - analytics.sessionStart,
      topDomains: Object.entries(analytics.domains || {})
        .filter(([domain, count]) => 
          typeof domain === 'string' && Number.isInteger(count) && count > 0
        )
        .sort(([, a], [, b]) => (b || 0) - (a || 0))
        .slice(0, 10)
        .map(([domain, count]) => ({ domain, count }))
    };
  }

  test.it('calculates 0% block rate for no analysis', () => {
    const report = generateAnalyticsReport({
      analyzed: 0,
      blocked: 0,
      sessionStart: Date.now(),
      domains: {}
    });
    test.assertEqual(report.blockRate, '0%', 'Should be 0% for no analysis');
  });

  test.it('calculates 50% block rate', () => {
    const report = generateAnalyticsReport({
      analyzed: 100,
      blocked: 50,
      sessionStart: Date.now(),
      domains: {}
    });
    test.assertEqual(report.blockRate, '50.00%', 'Should calculate correct percentage');
  });

  test.it('calculates 0% block rate with no blocks', () => {
    const report = generateAnalyticsReport({
      analyzed: 100,
      blocked: 0,
      sessionStart: Date.now(),
      domains: {}
    });
    test.assertEqual(report.blockRate, '0.00%', 'Should be 0% with no blocks');
  });

  test.it('filters invalid domains', () => {
    const report = generateAnalyticsReport({
      analyzed: 10,
      blocked: 5,
      sessionStart: Date.now(),
      domains: {
        'example.com': 5,
        'bad.com': 2
      }
    });
    test.assertTrue(report.topDomains.length <= 2, 'Should filter invalid entries');
  });

  test.it('limits to top 10 domains', () => {
    const domains = {};
    for (let i = 0; i < 20; i++) {
      domains[`domain${i}.com`] = 100 - i;
    }
    const report = generateAnalyticsReport({
      analyzed: 100,
      blocked: 50,
      sessionStart: Date.now(),
      domains
    });
    test.assertTrue(report.topDomains.length <= 10, 'Should limit to 10 domains');
  });

  test.it('includes session duration', () => {
    const report = generateAnalyticsReport({
      analyzed: 10,
      blocked: 5,
      sessionStart: Date.now() - 5000,
      domains: {}
    });
    test.assertTrue(report.sessionDuration >= 5000, 'Should calculate session duration');
  });
});

// ============================================================================
// UNIT TESTS: Content Size Limiting
// ============================================================================

test.describe('Unit: Content Size Validation', () => {
  const MAX_CONTENT_LENGTH = 10000;

  function validateContentSize(content) {
    if (!content || typeof content !== 'string') return false;
    if (content.length > MAX_CONTENT_LENGTH) return false;
    return true;
  }

  test.it('accepts normal content', () => {
    test.assertTrue(validateContentSize('This is normal content'), 'Normal content should be valid');
  });

  test.it('accepts max size', () => {
    const maxContent = 'a'.repeat(MAX_CONTENT_LENGTH);
    test.assertTrue(validateContentSize(maxContent), 'Max size should be valid');
  });

  test.it('rejects oversized content', () => {
    const oversized = 'a'.repeat(MAX_CONTENT_LENGTH + 1);
    test.assertFalse(validateContentSize(oversized), 'Oversized content should be rejected');
  });

  test.it('rejects null', () => {
    test.assertFalse(validateContentSize(null), 'Null should be rejected');
  });

  test.it('rejects non-string', () => {
    test.assertFalse(validateContentSize(12345), 'Non-string should be rejected');
  });
});

// ============================================================================
// UNIT TESTS: Error Handling
// ============================================================================

test.describe('Unit: Error Handling', () => {
  function safeAnalyze(content) {
    try {
      if (!content || typeof content !== 'string') {
        throw new Error('Invalid content');
      }
      return { success: true, data: content.length };
    } catch (e) {
      return { success: false, error: e.message };
    }
  }

  test.it('handles valid input', () => {
    const result = safeAnalyze('test');
    test.assertTrue(result.success, 'Should succeed with valid input');
  });

  test.it('catches null error', () => {
    const result = safeAnalyze(null);
    test.assertFalse(result.success, 'Should fail with null');
    test.assertExists(result.error, 'Should have error message');
  });

  test.it('catches type error', () => {
    const result = safeAnalyze(123);
    test.assertFalse(result.success, 'Should fail with non-string');
  });

  test.it('continues after error', () => {
    const result1 = safeAnalyze(null);
    const result2 = safeAnalyze('test');
    test.assertTrue(result2.success, 'Should recover from error');
  });
});

// ============================================================================
// RUN TESTS
// ============================================================================

const success = test.report();
process.exit(success ? 0 : 1);
