/**
 * Copyright (c) 2026 Ryan P. Walsh. All rights reserved.
 * Proprietary commercial software published for public reference only.
 * No license is granted to use, copy, modify, distribute, or create derivative works.
 */

/**
 * UNIT TESTS - AI Content Blocker Pro
 * Test individual functions in isolation
 * Run with: node test/unit.test.js
 */

'use strict';

// Test Framework (using simple assertions - no dependencies)
class TestRunner {
  constructor() {
    this.tests = [];
    this.passed = 0;
    this.failed = 0;
  }

  describe(suiteName, fn) {
    console.log(`\n${suiteName}`);
    fn();
  }

  it(testName, fn) {
    try {
      fn();
      this.passed++;
      console.log(`  ✓ ${testName}`);
    } catch (error) {
      this.failed++;
      console.error(`  ✗ ${testName}`);
      console.error(`    ${error.message}`);
    }
  }

  assertEqual(actual, expected, message) {
    if (actual !== expected) {
      throw new Error(`${message || 'Assertion failed'}: expected ${expected}, got ${actual}`);
    }
  }

  assertTrue(value, message) {
    if (value !== true) {
      throw new Error(message || 'Expected true');
    }
  }

  assertFalse(value, message) {
    if (value !== false) {
      throw new Error(message || 'Expected false');
    }
  }

  assertExists(value, message) {
    if (value === null || value === undefined) {
      throw new Error(message || 'Expected value to exist');
    }
  }

  assertThrows(fn, message) {
    try {
      fn();
      throw new Error(message || 'Expected function to throw');
    } catch (e) {
      // Expected
    }
  }

  report() {
    console.log(`\n${'='.repeat(60)}`);
    console.log(`Tests Passed: ${this.passed}`);
    console.log(`Tests Failed: ${this.failed}`);
    console.log(`Total: ${this.passed + this.failed}`);
    console.log(`${'='.repeat(60)}\n`);
    return this.failed === 0;
  }
}

const test = new TestRunner();

// ============================================================================
// UNIT TESTS: text scoring (REAL functions, extracted from background.js)
// ============================================================================
// The previous suite tested a DUPLICATED copy of calculateKeywordScore, so
// the shipped scorer and its "tests" could drift apart silently -- and did:
// the copy still said 0.3/term after the real one changed. These helpers
// slice the real function bodies out of background.js (which cannot be
// require()d in node: chrome.* at top level), so a scorer change that the
// tests were not updated for FAILS instead of passing against a stale twin.

function extractFunction(source, name) {
  const start = source.indexOf(`function ${name}(`);
  if (start === -1) throw new Error(`${name} not found`);
  let depth = 0, i = source.indexOf('{', start);
  const open = i;
  for (; i < source.length; i++) {
    if (source[i] === '{') depth++;
    if (source[i] === '}') depth--;
    if (!depth) break;
  }
  const params = source.slice(source.indexOf('(', start) + 1, source.indexOf(')', start));
  const body = source.slice(open + 1, i);
  return new Function(...params.split(',').map(x => x.trim()).filter(Boolean), 'logError', body + ';')
    ;
}

const backgroundSource = require('fs').readFileSync(require('path').join(__dirname, '..', 'src', 'background.js'), 'utf8');
const realKeywordScore = (content, terms) => extractFunction(backgroundSource, 'calculateKeywordScore')(content, terms, () => {});
const realPatternScore = (content, type) => extractFunction(backgroundSource, 'calculatePatternScore')(content, type, () => {});
const realStructureScore = (content, type) => extractFunction(backgroundSource, 'calculateStructureScore')(content, type, () => {});

test.describe('Unit: calculateKeywordScore() [real implementation]', () => {
  test.it('returns 0 for empty content', () => {
    test.assertEqual(realKeywordScore('', ['ai-generated']), 0, 'Empty content should score 0');
  });

  test.it('returns 0 for no matched terms', () => {
    test.assertEqual(realKeywordScore('This is normal content', ['ai-generated', 'midjourney']), 0, 'No matches should score 0');
  });

  test.it('a single explicit disclosure is decisive (0.75)', () => {
    test.assertEqual(realKeywordScore('this was ai-generated', ['ai-generated']), 0.75, 'One disclosure = 0.75');
  });

  test.it('caps at 1.0 for multiple matches', () => {
    test.assertEqual(realKeywordScore('ai-generated by midjourney', ['ai-generated', 'midjourney']), 1, 'Two matches cap at 1.0');
  });

  test.it('handles invalid terms array', () => {
    test.assertEqual(realKeywordScore('ai-generated', null), 0, 'Should handle null terms');
  });
});

test.describe('Unit: scoring contract at default threshold', () => {
  const DEFAULT_CONFIDENCE = 0.5;
  const finalScore = (content, terms) => {
    const k = realKeywordScore(content.toLowerCase(), terms);
    const p = realPatternScore(content.toLowerCase(), 'text');
    const st = realStructureScore(content, 'text');
    // Mirrors background.js: corroboration bonus when disclosure and
    // pattern signals co-occur.
    const corroboration = k > 0 && p > 0 ? 0.2 : 0;
    return Math.min(1, k * 0.4 + p * 0.35 + st * 0.25 + corroboration);
  };

  test.it('default in DEFAULT_SETTINGS matches this contract', () => {
    test.assertTrue(/confidence:\s*0\.5,/.test(backgroundSource), 'DEFAULT_SETTINGS.confidence must be 0.5');
  });

  test.it('disclosure-bearing AI text badges at defaults', () => {
    const text = 'This article was ai-generated using modern tools. Content generated by AI systems is increasingly common.';
    const score = finalScore(text, ['ai-generated']);
    test.assertTrue(score > DEFAULT_CONFIDENCE, `disclosure text must badge (got ${score.toFixed(3)})`);
  });

  test.it('the hyphenated real-world disclosure form badges at defaults', () => {
    // "AI-generated" (hyphen) is the most common disclosure in the wild;
    // a space-only pattern separator scored it 0 -- verified live.
    const score = finalScore('This article was AI-generated as part of our automated content program.', ['ai-generated']);
    test.assertTrue(score > DEFAULT_CONFIDENCE, `hyphenated disclosure must badge (got ${score.toFixed(3)})`);
  });

  test.it('a bare tool-name mention with no pattern corroboration does not badge', () => {
    // Mentioning a tool is not disclosing generation: an article ABOUT
    // Midjourney must not badge on the name alone. (The literal token
    // "ai-generated" is inherently keyword+pattern at once, so it badges
    // by design -- that is a disclosure string, not a mention.)
    const score = finalScore('The artist discussed Midjourney at the conference last week.', ['ai-generated', 'midjourney']);
    test.assertTrue(score <= DEFAULT_CONFIDENCE, `bare tool mention must not badge (got ${score.toFixed(3)})`);
  });

  test.it('plain human text does not badge at defaults', () => {
    const text = 'My grandfather kept bees for forty years and never once wore gloves. He said the trick was moving slow in the morning. Furthermore, he was stubborn.';
    const score = finalScore(text, ['ai-generated', 'midjourney']);
    test.assertTrue(score <= DEFAULT_CONFIDENCE, `human text must not badge (got ${score.toFixed(3)})`);
  });

  test.it('undisclosed AI text is REACHABLE at defaults (the old 0.7 made it impossible)', () => {
    // Heuristic-only ceiling: pattern 0.9*0.35 + structure 1.0*0.25 = 0.565.
    const ceiling = 0.9 * 0.35 + 1.0 * 0.25;
    test.assertTrue(ceiling > DEFAULT_CONFIDENCE, 'heuristic ceiling must exceed the default threshold');
  });
});

// ============================================================================
// ============================================================================
// UNIT TESTS: Domain Blocking
// ============================================================================

test.describe('Unit: Domain Blocking/Whitelisting', () => {
  function isDomainBlocked(hostname, blockedDomains) {
    if (!blockedDomains || !Array.isArray(blockedDomains) || blockedDomains.length === 0) {
      return false;
    }
    return blockedDomains.some(blocked => 
      typeof blocked === 'string' && hostname.includes(blocked)
    );
  }

  test.it('returns false for empty blocklist', () => {
    test.assertFalse(isDomainBlocked('example.com', []), 'Empty list should not block');
  });

  test.it('returns false for null blocklist', () => {
    test.assertFalse(isDomainBlocked('example.com', null), 'Null should not block');
  });

  test.it('blocks exact domain match', () => {
    test.assertTrue(isDomainBlocked('evil.com', ['evil.com']), 'Exact match should block');
  });

  test.it('blocks subdomain match', () => {
    test.assertTrue(isDomainBlocked('sub.evil.com', ['evil.com']), 'Subdomain should block');
  });

  test.it('does not block non-matching domain', () => {
    test.assertFalse(isDomainBlocked('good.com', ['evil.com']), 'Non-match should not block');
  });

  test.it('filters non-string entries', () => {
    test.assertFalse(isDomainBlocked('example.com', [null, 123, undefined]), 'Non-strings should be filtered');
  });

  test.it('handles multiple blocked domains', () => {
    test.assertTrue(isDomainBlocked('bad.com', ['evil.com', 'bad.com', 'awful.com']), 'Should match second domain');
  });
});

// ============================================================================
// UNIT TESTS: Trial Period Calculation
// ============================================================================

test.describe('Unit: Trial Period Calculation', () => {
  function calculateTrialDaysRemaining(trialStart) {
    try {
      if (!trialStart || typeof trialStart !== 'number') {
        return 30;
      }
      const elapsed = Date.now() - trialStart;
      const daysElapsed = Math.floor(elapsed / (24 * 60 * 60 * 1000));
      const daysRemaining = Math.max(0, 30 - daysElapsed);
      return daysRemaining;
    } catch (e) {
      return 30;
    }
  }

  test.it('returns 30 for null start date', () => {
    const result = calculateTrialDaysRemaining(null);
    test.assertEqual(result, 30, 'Null should default to 30 days');
  });

  test.it('returns 30 for just installed', () => {
    const result = calculateTrialDaysRemaining(Date.now());
    test.assertEqual(result, 30, 'Just installed should be 30 days');
  });

  test.it('returns ~29 for 1 day old', () => {
    const oneDayAgo = Date.now() - (1 * 24 * 60 * 60 * 1000);
    const result = calculateTrialDaysRemaining(oneDayAgo);
    test.assertEqual(result, 29, 'One day old should be ~29 days');
  });

  test.it('returns 0 for expired trial', () => {
    const thirtyOneDaysAgo = Date.now() - (31 * 24 * 60 * 60 * 1000);
    const result = calculateTrialDaysRemaining(thirtyOneDaysAgo);
    test.assertEqual(result, 0, 'Expired should return 0');
  });

  test.it('never returns negative', () => {
    const hundredDaysAgo = Date.now() - (100 * 24 * 60 * 60 * 1000);
    const result = calculateTrialDaysRemaining(hundredDaysAgo);
    test.assertTrue(result >= 0, 'Should never be negative');
  });
});

// ============================================================================
// UNIT TESTS: Analytics Calculation
// ============================================================================

test.describe('Unit: Analytics Report Generation', () => {
  function generateAnalyticsReport(analytics) {
    const blockRate = analytics.analyzed > 0 
      ? ((analytics.blocked / analytics.analyzed) * 100).toFixed(2)
      : 0;
    
    return {
      totalAnalyzed: analytics.analyzed || 0,
      totalBlocked: analytics.blocked || 0,
      blockRate: `${blockRate}%`,
      sessionDuration: Date.now() - analytics.sessionStart,
      topDomains: Object.entries(analytics.domains || {})
        .filter(([domain, count]) => 
          typeof domain === 'string' && Number.isInteger(count) && count > 0
        )
        .sort(([, a], [, b]) => (b || 0) - (a || 0))
        .slice(0, 10)
        .map(([domain, count]) => ({ domain, count }))
    };
  }

  test.it('calculates 0% block rate for no analysis', () => {
    const report = generateAnalyticsReport({
      analyzed: 0,
      blocked: 0,
      sessionStart: Date.now(),
      domains: {}
    });
    test.assertEqual(report.blockRate, '0%', 'Should be 0% for no analysis');
  });

  test.it('calculates 50% block rate', () => {
    const report = generateAnalyticsReport({
      analyzed: 100,
      blocked: 50,
      sessionStart: Date.now(),
      domains: {}
    });
    test.assertEqual(report.blockRate, '50.00%', 'Should calculate correct percentage');
  });

  test.it('calculates 0% block rate with no blocks', () => {
    const report = generateAnalyticsReport({
      analyzed: 100,
      blocked: 0,
      sessionStart: Date.now(),
      domains: {}
    });
    test.assertEqual(report.blockRate, '0.00%', 'Should be 0% with no blocks');
  });

  test.it('filters invalid domains', () => {
    const report = generateAnalyticsReport({
      analyzed: 10,
      blocked: 5,
      sessionStart: Date.now(),
      domains: {
        'example.com': 5,
        'bad.com': 2
      }
    });
    test.assertTrue(report.topDomains.length <= 2, 'Should filter invalid entries');
  });

  test.it('limits to top 10 domains', () => {
    const domains = {};
    for (let i = 0; i < 20; i++) {
      domains[`domain${i}.com`] = 100 - i;
    }
    const report = generateAnalyticsReport({
      analyzed: 100,
      blocked: 50,
      sessionStart: Date.now(),
      domains
    });
    test.assertTrue(report.topDomains.length <= 10, 'Should limit to 10 domains');
  });

  test.it('includes session duration', () => {
    const report = generateAnalyticsReport({
      analyzed: 10,
      blocked: 5,
      sessionStart: Date.now() - 5000,
      domains: {}
    });
    test.assertTrue(report.sessionDuration >= 5000, 'Should calculate session duration');
  });
});

// ============================================================================
// UNIT TESTS: Content Size Limiting
// ============================================================================

test.describe('Unit: Content Size Validation', () => {
  const MAX_CONTENT_LENGTH = 10000;

  function validateContentSize(content) {
    if (!content || typeof content !== 'string') return false;
    if (content.length > MAX_CONTENT_LENGTH) return false;
    return true;
  }

  test.it('accepts normal content', () => {
    test.assertTrue(validateContentSize('This is normal content'), 'Normal content should be valid');
  });

  test.it('accepts max size', () => {
    const maxContent = 'a'.repeat(MAX_CONTENT_LENGTH);
    test.assertTrue(validateContentSize(maxContent), 'Max size should be valid');
  });

  test.it('rejects oversized content', () => {
    const oversized = 'a'.repeat(MAX_CONTENT_LENGTH + 1);
    test.assertFalse(validateContentSize(oversized), 'Oversized content should be rejected');
  });

  test.it('rejects null', () => {
    test.assertFalse(validateContentSize(null), 'Null should be rejected');
  });

  test.it('rejects non-string', () => {
    test.assertFalse(validateContentSize(12345), 'Non-string should be rejected');
  });
});

// ============================================================================
// UNIT TESTS: Error Handling
// ============================================================================

test.describe('Unit: Error Handling', () => {
  function safeAnalyze(content) {
    try {
      if (!content || typeof content !== 'string') {
        throw new Error('Invalid content');
      }
      return { success: true, data: content.length };
    } catch (e) {
      return { success: false, error: e.message };
    }
  }

  test.it('handles valid input', () => {
    const result = safeAnalyze('test');
    test.assertTrue(result.success, 'Should succeed with valid input');
  });

  test.it('catches null error', () => {
    const result = safeAnalyze(null);
    test.assertFalse(result.success, 'Should fail with null');
    test.assertExists(result.error, 'Should have error message');
  });

  test.it('catches type error', () => {
    const result = safeAnalyze(123);
    test.assertFalse(result.success, 'Should fail with non-string');
  });

  test.it('continues after error', () => {
    const result1 = safeAnalyze(null);
    const result2 = safeAnalyze('test');
    test.assertTrue(result2.success, 'Should recover from error');
  });
});


// ============================================================================
// SIGNATURE MATCHING (context-aware, word-boundary)
// ============================================================================
// The matcher used to be a bare substring scan over extracted bytes, so
// two-letter signatures ("MJ", "IF") matched random binary constantly -- a
// live capture badged an ad 73% on "AI signature in webp_scan: MJ". These
// tests load the real checkAISignaturesInString body from the content script
// (which cannot be require()d in node because it touches window at top
// level) and pin the contract: raw-scan sources reject ambiguous/short
// signatures entirely, every match is word-boundary, structured metadata
// fields may still match short tool tags as whole tokens.
test.describe('Unit: AI Signature Matching', () => {
  const fs = require('fs');
  const path = require('path');
  const src = fs.readFileSync(path.join(__dirname, '..', 'src', 'content-agent-orange.js'), 'utf8');
  const start = src.indexOf('checkAISignaturesInString(str, result, source) {');
  const body = src.slice(start);
  let depth = 0, end = body.indexOf('{');
  for (let i = end; i < body.length; i++) {
    if (body[i] === '{') depth++;
    if (body[i] === '}') depth--;
    if (!depth) { end = i + 1; break; }
  }
  const fnBody = body.slice(body.indexOf('{') + 1, end - 1).replaceAll('this.', '');
  const SIGS = { exifSoftware: ['Midjourney', 'MJ', 'IF', 'DALL-E', 'Stable Diffusion'], c2paSignatures: [] };
  const check = new Function('str', 'result', 'source', 'AI_SIGNATURES', fnBody + ';');
  const hits = (str, source) => {
    const r = { confidence: 0, indicators: [], forensics: {} };
    try { check(str, r, source, SIGS); } catch (e) { /* helper refs past the sig loop */ }
    return r.indicators.map(i => i.indicator);
  };

  test.it('raw byte scans never match two-letter signatures', () => {
    test.assertEqual(hits('xx9fmjq7binary IF junk', 'webp_scan').length, 0, 'MJ/IF must not match raw bytes');
  });

  test.it('raw byte scans still match distinctive whole words', () => {
    test.assertTrue(hits('made with midjourney v6', 'webp_scan').some(h => h.includes('Midjourney')), 'real tool name should match');
  });

  test.it('structured EXIF fields may match short tool tags as whole tokens', () => {
    test.assertTrue(hits('software: MJ build 6', 'exif').some(h => h.includes('MJ')), 'whole-token MJ in EXIF should match');
  });

  test.it('no substring matches even in structured fields', () => {
    test.assertEqual(hits('dmjpeg encoder pipeline', 'exif').length, 0, 'mj inside mjpeg must not match');
  });

  test.it('regex metacharacters in signatures are escaped', () => {
    test.assertTrue(hits('created by dall-e 3', 'exif').some(h => h.includes('DALL-E')), 'DALL-E must match literally');
  });
});

// ============================================================================
// C2PA PROVENANCE vs AI VERDICT (real function body)
// ============================================================================
// A signed credential used to add +0.6 AI confidence just for existing, so a
// signed camera photo scored as AI for carrying its papers. The contract now:
// presence sets forensics.hasC2PA with NO confidence bump (the UI shows a
// neutral provenance badge instead); only an AI-tool marker or a
// trainedAlgorithmicMedia assertion inside the credential is an AI verdict,
// and that floors confidence at 0.85.
test.describe('Unit: C2PA Provenance Split', () => {
  const fs = require('fs');
  const path = require('path');
  const src = fs.readFileSync(path.join(__dirname, '..', 'src', 'content-agent-orange.js'), 'utf8');
  const start = src.indexOf('checkAISignaturesInString(str, result, source) {');
  const body = src.slice(start);
  let depth = 0, end = body.indexOf('{');
  for (let i = end; i < body.length; i++) {
    if (body[i] === '{') depth++;
    if (body[i] === '}') depth--;
    if (!depth) { end = i + 1; break; }
  }
  const fnBody = body.slice(body.indexOf('{') + 1, end - 1).replaceAll('this.', '');
  // Empty exifSoftware isolates the C2PA loop (tool names would match it first).
  const SIGS = { exifSoftware: [], c2paSignatures: ['c2pa', 'contentcredentials', 'adobe:ai', 'openai:dall-e', 'midjourney'] };
  const check = new Function('str', 'result', 'source', 'AI_SIGNATURES', fnBody + ';');
  const run = (str) => {
    const r = { confidence: 0, indicators: [], forensics: {} };
    try { check(str, r, 'xmp', SIGS); } catch (e) { /* helper refs past the sig loops */ }
    return r;
  };

  test.it('signed credential alone adds ZERO AI confidence', () => {
    const r = run('urn:c2pa:manifest signed by camera vendor');
    test.assertTrue(r.forensics.hasC2PA === true, 'hasC2PA must be set');
    test.assertEqual(r.confidence, 0, 'presence must not score as AI');
    test.assertTrue(!r.forensics.c2paAIAsserted, 'no AI assertion');
  });

  test.it('signed credential alone still surfaces a provenance indicator', () => {
    const r = run('contentcredentials manifest v1');
    test.assertTrue(r.indicators.some(i => i.indicator.includes('Signed Content Credentials')), 'neutral indicator expected');
  });

  test.it('AI-tool marker inside credential floors confidence at 0.85', () => {
    const r = run('c2pa manifest generator openai:dall-e 3');
    test.assertTrue(r.forensics.c2paAIAsserted === true, 'AI asserted');
    test.assertTrue(r.confidence >= 0.85, 'confidence floored, got ' + r.confidence);
  });

  test.it('trainedAlgorithmicMedia assertion is an AI verdict', () => {
    const r = run('c2pa digitalsourcetype trainedAlgorithmicMedia');
    test.assertTrue(r.forensics.c2paAIAsserted === true, 'AI asserted');
    test.assertTrue(r.confidence >= 0.85, 'confidence floored, got ' + r.confidence);
  });
});

// ============================================================================
// RUN TESTS
// ============================================================================

const success = test.report();
process.exit(success ? 0 : 1);
