/*
 * Copyright (c) 2026 Ryan P. Walsh
 * SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
 * Noncommercial use is free; commercial use requires a separate
 * license from the author. See LICENSE.
 */

// Background service worker for AI Content Blocker Pro
// Detection, analytics, and sync (local-first; no licensing machinery -- proprietary code, published for reference)
// Version 2.0.0 - Production Ready

'use strict';

const DEFAULT_SETTINGS = {
  blockedTerms: [
    'generated by ai',
    'ai-generated',
    'artificial intelligence generated',
    'machine learning generated',
    'midjourney',
    'dall-e',
    'stable diffusion'
  ],
  enabled: true,
  blockImages: true,
  blockText: true,
  // 0.55, not 0.7: text scoring is keyword*0.4 + pattern*0.35 +
  // structure*0.25, so without an explicit disclosure keyword the
  // reachable maximum is 0.60 -- a 0.7 default made detection of
  // UNDISCLOSED AI text mathematically impossible, which is the entire
  // point of heuristic detection. 0.55 keeps keyword-only hits (0.40)
  // below threshold while letting strong pattern+structure evidence badge.
  // 0.5, not 0.7. The text scorer is keyword*0.4 + pattern*0.35 +
  // structure*0.25 with component caps 1.0 / 0.9 / 1.0, so the ceiling
  // WITHOUT an explicit disclosure keyword is 0.315 + 0.25 = 0.565: at the
  // old 0.7 default, detection of undisclosed AI text was mathematically
  // impossible, and even one disclosure hit plus every heuristic maxed
  // reached only 0.685. 0.5 lets a single explicit disclosure (0.30) plus
  // ordinary pattern evidence badge, and heuristic-only text must still be
  // near its ceiling -- rich in AI patterns AND structure -- to cross.
  confidence: 0.5,
  analyticsEnabled: true,
  blockedDomains: [],
  whitelistedDomains: [],
  // How (if at all) to visually modify detected content.
  // 'none' = badge/flag only (no blur/hide/watermark)
  blockingMode: 'none', // none, blur, hide, watermark
  blockVideo: false,
  blockVideos: false,
  enableDeepfakeScan: false,
  version: '2.0.0'
};

// Trial period: 30 days in milliseconds

// Analytics tracking
const analytics = {
  sessionStart: Date.now(),
  blocked: 0,
  analyzed: 0,
  domains: {},
  hourly: {},
  daily: {}
};

// Error logger
function logError(context, error) {
  console.error(`[AIB Error] ${context}:`, error);
  chrome.storage.local.get('errors', (data) => {
    const errors = data.errors || [];
    errors.push({
      timestamp: Date.now(),
      context,
      message: error?.message || String(error)
    });
    // Keep last 100 errors
    if (errors.length > 100) {
      errors.shift();
    }
    chrome.storage.local.set({ errors });
  });
}

// ============================================================================
// LOCAL FEEDBACK HELPERS
// ============================================================================

async function sha256Base64Url(input) {
  try {
    const data = (typeof input === 'string') ? new TextEncoder().encode(input) : input;
    const digest = await crypto.subtle.digest('SHA-256', data);
    const bytes = new Uint8Array(digest);
    let b64 = btoa(String.fromCharCode(...bytes));
    // base64url
    b64 = b64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
    return b64;
  } catch {
    return null;
  }
}

function getDayBucket(ts = Date.now()) {
  return Math.floor(ts / (24 * 60 * 60 * 1000));
}


// Initialize extension
chrome.runtime.onInstalled.addListener((details) => {
  try {
    if (details.reason === 'install') {
      chrome.storage.sync.get(null, (items) => {
        try {
          if (Object.keys(items).length === 0) {
            const settings = {
              ...DEFAULT_SETTINGS,
            };
            chrome.storage.sync.set(settings);
          }
        } catch (e) {
          logError('Failed to initialize settings', e);
        }
      });
      // Show onboarding on next page visit, not immediately
      chrome.storage.local.set({ showOnboarding: true });
    } else if (details.reason === 'update') {
      migrateSettings();
    }
  } catch (e) {
    logError('Extension installation failed', e);
  }
});


// Migrate settings from old versions
function migrateSettings() {
  try {
    chrome.storage.sync.get(null, (items) => {
      try {
        const version = items.version || '1.0.0';
        if (version !== '2.0.0') {
          const updated = { 
            ...items, 
            ...DEFAULT_SETTINGS,
            version: '2.0.0',
          };
          chrome.storage.sync.set(updated);
        }
      } catch (e) {
        logError('Settings migration failed', e);
      }
    });
  } catch (e) {
    logError('Migration initialization failed', e);
  }
}

// Listen for messages from content scripts and popup
// ============================================================================
// SLOP METER: per-tab flagged-content count on the toolbar icon
// ============================================================================
// The popup already knows; the icon should too. Users get per-page AI
// density at a glance -- the number of flagged items on THIS tab -- without
// opening anything. Cleared on navigation and tab close.
const tabFlagCounts = new Map();

function bumpSlopMeter(tabId) {
  if (typeof tabId !== 'number' || tabId < 0) return;
  const next = (tabFlagCounts.get(tabId) || 0) + 1;
  tabFlagCounts.set(tabId, next);
  try {
    chrome.action.setBadgeBackgroundColor({ tabId, color: '#e8590c' });
    chrome.action.setBadgeText({ tabId, text: next > 99 ? '99+' : String(next) });
  } catch (e) { /* tab may be gone */ }
}

chrome.tabs.onUpdated.addListener((tabId, changeInfo) => {
  if (changeInfo.status === 'loading') {
    tabFlagCounts.delete(tabId);
    try { chrome.action.setBadgeText({ tabId, text: '' }); } catch (e) { /* ignore */ }
  }
});
chrome.tabs.onRemoved.addListener((tabId) => tabFlagCounts.delete(tabId));

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  try {
    if (!request || typeof request !== 'object') {
      sendResponse({ error: 'Invalid request' });
      return true;
    }

    if (request.action === 'getSettings') {
      chrome.storage.sync.get(null, (response) => {
        try {
          // Normalize settings keys across versions.
          // Historical inconsistency: some builds used blockVideos (plural) while
          // the content script expects blockVideo (singular).
          response = response || {};
          if (typeof response.blockVideo === 'undefined' && typeof response.blockVideos !== 'undefined') {
            response.blockVideo = response.blockVideos;
          }
          if (typeof response.blockVideos === 'undefined' && typeof response.blockVideo !== 'undefined') {
            response.blockVideos = response.blockVideo;
          }

          // Ensure new media toggles have safe defaults even if storage is old.
          if (typeof response.blockVideo === 'undefined') response.blockVideo = DEFAULT_SETTINGS.blockVideo;
          if (typeof response.blockVideos === 'undefined') response.blockVideos = response.blockVideo;
          if (typeof response.blockAudio === 'undefined') response.blockAudio = true;
          if (typeof response.blockEmbeds === 'undefined') response.blockEmbeds = true;
          if (typeof response.blockDocuments === 'undefined') response.blockDocuments = true;
          if (typeof response.blockCanvas === 'undefined') response.blockCanvas = true;
          if (typeof response.goHard === 'undefined') response.goHard = false;

          sendResponse(response || DEFAULT_SETTINGS);
        } catch (e) {
          logError('getSettings failed', e);
          sendResponse(DEFAULT_SETTINGS);
        }
      });
      return true;
    }

    if (request.action === 'saveSettings') {
      if (!request.settings || typeof request.settings !== 'object') {
        sendResponse({ success: false, error: 'Invalid settings' });
        return true;
      }
      chrome.storage.sync.set(request.settings, () => {
        sendResponse({ success: true });
      });
      return true;
    }

    if (request.action === 'analyzeContent') {
      if (!request.content || !request.type) {
        sendResponse({ error: 'Missing required parameters' });
        return true;
      }
      analyzeContent(request.content, request.type, (result) => {
        sendResponse(result);
        if (result && result.isAiGenerated) bumpSlopMeter(sender?.tab?.id);
        if (request.url) {
          trackAnalytics(request.url, result, request.type);
        }
      });
      return true;
    }

    if (request.action === 'getAnalytics') {
      sendResponse(getAnalyticsReport());
      return true;
    }

    if (request.action === 'getLearningState') {
      chrome.storage.local.get(['aoDomainPriors'], (store) => {
        try {
          sendResponse({
            domainPriors: (store.aoDomainPriors && typeof store.aoDomainPriors === 'object') ? store.aoDomainPriors : {},
          });
        } catch (e) {
          logError('getLearningState failed', e);
          sendResponse({ domainPriors: {} });
        }
      });
      return true;
    }

    // Unified analytics events from content scripts (Agent Orange pipeline)
    if (request.action === 'trackAnalyticsEvent') {
      try {
        const url = request?.data?.url || sender?.url || '';
        const resultLike = {
          isAiGenerated: true,
          confidence: typeof request?.data?.confidence === 'number' ? request.data.confidence : 0
        };
        trackAnalytics(url, resultLike, request?.data?.type || 'unknown');
        sendResponse({ success: true });
      } catch (e) {
        logError('trackAnalyticsEvent failed', e);
        sendResponse({ success: false });
      }
      return true;
    }

    // Optional: accept periodic performance metrics from content scripts
    if (request.action === 'updateMetrics') {
      try {
        chrome.storage.local.set({ lastContentScriptMetrics: request.data, lastMetricsUpdate: Date.now() });
        sendResponse({ success: true });
      } catch (e) {
        logError('updateMetrics failed', e);
        sendResponse({ success: false });
      }
      return true;
    }

    // -----------------------------------------------------------------------
    // User feedback (local learning)
    // -----------------------------------------------------------------------
    if (request.action === 'recordUserFeedback') {
      try {
        const fb = request?.data;
        const label = fb?.label;
        if (!label) {
          sendResponse({ success: false, error: 'Missing label' });
          return true;
        }

        const url = fb?.url || sender?.url || '';
        let domain = '';
        try {
          domain = url ? (new URL(url)).hostname : '';
        } catch {
          domain = '';
        }

  chrome.storage.local.get(['aoFeedbackLog', 'aoDomainPriors'], (store) => {
          try {
            const log = Array.isArray(store.aoFeedbackLog) ? store.aoFeedbackLog : [];
            const priors = (store.aoDomainPriors && typeof store.aoDomainPriors === 'object') ? store.aoDomainPriors : {};

            // Keep a bounded local log for debugging/export (no network).
            log.push({
              ...fb,
              domain,
              ts: fb?.ts || Date.now(),
            });
            const MAX_LOG = 500;
            if (log.length > MAX_LOG) log.splice(0, log.length - MAX_LOG);

            // Simple online update for per-domain prior.
            // prior in [0,1] where 1 means "site tends to be AI".
            if (domain) {
              const prev = priors[domain] || { prior: 0.5, n: 0 };
              const y = label === 'confirm_ai' ? 1 : (label === 'dismiss_not_ai' ? 0 : null);
              if (y !== null) {
                const n = (prev.n || 0) + 1;
                const lr = 1 / Math.min(50, n); // diminishing learning rate
                const prior = clamp01((prev.prior ?? 0.5) * (1 - lr) + y * lr);
                priors[domain] = { prior, n, updatedAt: Date.now() };
              }
            }

            chrome.storage.local.set({
              aoFeedbackLog: log,
              aoDomainPriors: priors,
            }, () => sendResponse({ success: true, domain }));
          } catch (e) {
            logError('recordUserFeedback storage update failed', e);
            sendResponse({ success: false });
          }
        });
      } catch (e) {
        logError('recordUserFeedback failed', e);
        sendResponse({ success: false });
      }

      return true;
    }

    // -----------------------------------------------------------------------
    // Feature-level votes (from overlay popover): stored locally only.
    // -----------------------------------------------------------------------
    if (request.action === 'recordFeatureVotes') {
      try {
        const payload = request?.payload || {};
        const rawVotes = Array.isArray(payload?.featureVotes) ? payload.featureVotes : [];
        const cleanedFeatureIds = rawVotes
          .map(v => (typeof v?.featureId === 'string' ? v.featureId.trim() : ''))
          .filter(Boolean)
          .filter(x => /^[a-zA-Z0-9:_\-\.]{1,140}$/.test(x))
          .slice(0, 32);

        if (cleanedFeatureIds.length === 0) {
          sendResponse({ success: false, error: 'no_features' });
          return true;
        }

        // For now, we treat "Apply" as: user affirms these features are valid.
        // That corresponds to voting "ai" for the selected element.
        // (If we add feature polarity to server later, we can encode up/down.)
        const feedback = {
          ts: Date.now(),
          label: 'confirm_ai',
          confidence: typeof payload?.confidence === 'number' ? payload.confidence : null,
          featureIds: cleanedFeatureIds,
        };

        chrome.storage.local.get(['aoFeatureVoteLog'], (store) => {
          try {
            const log = Array.isArray(store.aoFeatureVoteLog) ? store.aoFeatureVoteLog : [];
            log.push({ ts: Date.now(), featureVotes: rawVotes, featureIds: cleanedFeatureIds });
            const MAX_LOG = 500;
            if (log.length > MAX_LOG) log.splice(0, log.length - MAX_LOG);
            chrome.storage.local.set({ aoFeatureVoteLog: log }, () => sendResponse({ success: true }));
          } catch (e) {
            logError('recordFeatureVotes storage failed', e);
            sendResponse({ success: false });
          }
        });

        return true;
      } catch (e) {
        logError('recordFeatureVotes failed', e);
        sendResponse({ success: false });
        return true;
      }
    }

  } catch (e) {
    logError('Message handler failed', e);
    sendResponse({ error: 'Internal error' });
  }

  return true;
});

function clamp01(x) {
  if (typeof x !== 'number' || Number.isNaN(x)) return 0;
  return Math.max(0, Math.min(1, x));
}

// Advanced content analysis
function analyzeContent(content, type = 'text', callback) {
  try {
    if (!content || typeof content !== 'string') {
      callback({ 
        isAiGenerated: false, 
        confidence: 0, 
        error: 'Invalid content'
      });
      return;
    }

    chrome.storage.sync.get(['blockedTerms', 'confidence'], (data) => {
      try {
        const blockedTerms = data.blockedTerms || DEFAULT_SETTINGS.blockedTerms;
        const confidence = data.confidence || DEFAULT_SETTINGS.confidence;
        
        if (!Array.isArray(blockedTerms)) {
          callback({ 
            isAiGenerated: false, 
            confidence: 0, 
            error: 'Invalid blocked terms configuration'
          });
          return;
        }

        const contentLower = content.toLowerCase().substring(0, 10000); // Limit size
        
        // Multiple scoring methods
        let keywordScore = calculateKeywordScore(contentLower, blockedTerms);
        let patternScore = calculatePatternScore(contentLower, type);
        let structureScore = calculateStructureScore(content, type);
        
        // Weighted combination, plus corroboration: an explicit disclosure
        // term CO-OCCURRING with generation-pattern language is near-certain
        // AI content, while either signal alone stays sub-threshold (a news
        // article merely quoting "ai-generated" should not auto-badge; the
        // feedback buttons exist for the borderline). Without this, even
        // disclosure + pattern scored 0.405 and could not reach the 0.5
        // default.
        const corroboration = keywordScore > 0 && patternScore > 0 ? 0.2 : 0;
        const finalScore = Math.min(1, (keywordScore * 0.4) + (patternScore * 0.35) + (structureScore * 0.25) + corroboration);
        
        const matchedTerms = blockedTerms.filter(term => 
          typeof term === 'string' && contentLower.includes(term.toLowerCase())
        );

        callback({
          isAiGenerated: finalScore > confidence,
          confidence: Math.min(Math.max(finalScore, 0), 1),
          matchedTerms,
          keywordScore: Math.min(Math.max(keywordScore, 0), 1),
          patternScore: Math.min(Math.max(patternScore, 0), 1),
          structureScore: Math.min(Math.max(structureScore, 0), 1),
          analysis: {
            type,
            timestamp: Date.now(),
            method: 'hybrid'
          }
        });
      } catch (e) {
        logError('Content analysis processing failed', e);
        callback({ 
          isAiGenerated: false, 
          confidence: 0, 
          error: 'Analysis failed'
        });
      }
    });
  } catch (e) {
    logError('analyzeContent initialization failed', e);
    callback({ 
      isAiGenerated: false, 
      confidence: 0, 
      error: 'Fatal error'
    });
  }
}

function calculateKeywordScore(content, terms) {
  try {
    let score = 0;
    const validTerms = Array.isArray(terms) ? terms.filter(t => typeof t === 'string') : [];
    
    validTerms.forEach(term => {
      // An explicit disclosure term ("ai-generated", "midjourney"...) is the
      // highest-precision signal this scorer has; at 0.3 a single hit
      // contributed 0.12 after weighting and even disclosure-bearing text
      // could never reach the old 0.7 threshold. 0.75 makes one explicit
      // disclosure decisive-but-not-certain, two conclusive.
      if (content.includes(term.toLowerCase())) {
        score += 0.75;
      }
    });
    return Math.min(score, 1);
  } catch (e) {
    logError('Keyword score calculation failed', e);
    return 0;
  }
}

function calculatePatternScore(content, type) {
  try {
    let score = 0;
    
    // AI-related patterns. [\s-]+ not \s+: the single most common
    // real-world disclosure form is hyphenated ("AI-generated"), and a
    // space-only separator scored it 0 on exactly the text this signal
    // exists to catch -- verified live in the extension's own service
    // worker (keywordScore 0.75, patternScore 0, no badge).
    const aiPatterns = [
      /\b(generated|created|made)[\s-]+(by|with|using)[\s-]+(ai|ml|neural|gpt)/gi,
      /\b(ai|artificial intelligence|machine learning)[\s-]+(generated|created|made)\b/gi,
      /\b(powered[\s-]+by|using)[\s-]+(openai|anthropic|stability|midjourney)/gi
    ];
    
    aiPatterns.forEach(pattern => {
      try {
        if (pattern.test(content)) {
          score += 0.3;
        }
      } catch (e) {
        // Skip invalid patterns
      }
    });
    
    return Math.min(score, 1);
  } catch (e) {
    logError('Pattern score calculation failed', e);
    return 0;
  }
}

function calculateStructureScore(content, type) {
  try {
    // Check linguistic and structural patterns
    let score = 0;
    
    if (type === 'text' && content && typeof content === 'string') {
      // Repetitive phrases common in AI output
      const sentences = content.match(/[^.!?]+[.!?]/g) || [];
      if (sentences.length > 3) {
        const firstWords = sentences.slice(0, 3).map(s => {
          const words = s.trim().split(/\s+/);
          return words.length > 0 ? words[0] : '';
        }).filter(w => w);
        if (firstWords.length > 1 && new Set(firstWords).size < 3) {
          score += 0.2; // Repetitive opening words
        }
      }
      
      // Check for overly formal language
      const formalWords = (content.match(/\b(furthermore|moreover|additionally|consequently)\b/gi) || []).length;
      if (formalWords > 2) {
        score += 0.15;
      }
    }
    
    return Math.min(score, 1);
  } catch (e) {
    logError('Structure score calculation failed', e);
    return 0;
  }
}

// Analytics tracking
function trackAnalytics(url, result, type) {
  try {
    if (!url || typeof url !== 'string') return;
    
    analytics.analyzed++;
    if (result && result.isAiGenerated) {
      analytics.blocked++;
    }
    
    // Track by domain
    try {
      const urlObj = new URL(url);
      const domain = urlObj.hostname;
      if (domain) {
        analytics.domains[domain] = (analytics.domains[domain] || 0) + 1;
      }
    } catch (e) {
      // Invalid URL, skip domain tracking
    }
    
    // Save analytics periodically (every 50 analyses)
    if (analytics.analyzed % 50 === 0) {
      saveAnalytics();
    }
  } catch (e) {
    logError('Analytics tracking failed', e);
  }
}

function saveAnalytics() {
  try {
    const timestamp = new Date().toISOString().split('T')[0];
    chrome.storage.local.set({
      [`analytics_${timestamp}`]: analytics,
      lastAnalyticsUpdate: Date.now()
    });
  } catch (e) {
    logError('Analytics save failed', e);
  }
}

function getAnalyticsReport() {
  try {
    const blockRate = analytics.analyzed > 0 
      ? ((analytics.blocked / analytics.analyzed) * 100).toFixed(2)
      : 0;
    
    return {
      totalAnalyzed: analytics.analyzed || 0,
      totalBlocked: analytics.blocked || 0,
      blockRate: `${blockRate}%`,
      sessionDuration: Date.now() - analytics.sessionStart,
      topDomains: Object.entries(analytics.domains || {})
        .sort(([, a], [, b]) => (b || 0) - (a || 0))
        .slice(0, 10)
        .map(([domain, count]) => ({ domain, count }))
    };
  } catch (e) {
    logError('Analytics report generation failed', e);
    return {
      totalAnalyzed: 0,
      totalBlocked: 0,
      blockRate: '0%',
      sessionDuration: 0,
      topDomains: [],
      error: 'Failed to generate report'
    };
  }
}





// Context menu for quick actions
// Remove all existing context menus first to prevent duplicate ID errors
chrome.contextMenus.removeAll(() => {
  try {
    chrome.contextMenus.create({
      id: 'analyzeSelection',
      title: 'Inspect with SlopBlocker',
      contexts: ['selection']
    }, () => {
      // Check for errors but don't crash if it already exists
      if (chrome.runtime.lastError) {
        console.warn('[Background] Context menu warning:', chrome.runtime.lastError.message);
      }
    });

    chrome.contextMenus.onClicked.addListener((info, tab) => {
      try {
        if (info.menuItemId === 'analyzeSelection') {
          // The content script re-reads its own selection: exact bytes
          // (including invisible characters) survive, where
          // info.selectionText collapses whitespace.
          if (tab && tab.id) {
            chrome.tabs.sendMessage(tab.id, { action: 'inspectSelection' }).catch(() => {});
          }
        }
      } catch (e) {
        logError('Context menu click handler failed', e);
      }
    });
  } catch (e) {
    logError('Failed to create context menu', e);
  }
});

// Performance optimization: Clean up old analytics data
try {
  chrome.alarms.create('cleanupAnalytics', { periodInMinutes: 1440 }); // Daily

  chrome.alarms.onAlarm.addListener((alarm) => {
    try {
      if (alarm && alarm.name === 'cleanupAnalytics') {
        chrome.storage.local.get(null, (items) => {
          try {
            const today = new Date().toISOString().split('T')[0];
            const keysToRemove = [];
            Object.keys(items || {}).forEach(key => {
              if (key.startsWith('analytics_') && !key.includes(today)) {
                const dateStr = key.replace('analytics_', '');
                const itemDate = new Date(dateStr);
                if (Date.now() - itemDate.getTime() > 30 * 24 * 60 * 60 * 1000) {
                  keysToRemove.push(key);
                }
              }
            });
            if (keysToRemove.length > 0) {
              chrome.storage.local.remove(keysToRemove);
            }
          } catch (e) {
            logError('Analytics cleanup processing failed', e);
          }
        });
      }
    } catch (e) {
      logError('Alarm handler failed', e);
    }
  });
} catch (e) {
  logError('Alarm creation failed', e);
}

