/*
 * Copyright (c) 2026 Ryan Walsh. All rights reserved.
 * Proprietary commercial software published for public reference only.
 * No license is granted to use, copy, modify, distribute, or create derivative works.
 */

// Background service worker for AI Content Blocker Pro
// Enterprise-grade detection, analytics, licensing, and sync
// Version 2.0.0 - Production Ready

'use strict';

const DEFAULT_SETTINGS = {
  blockedTerms: [
    'generated by ai',
    'ai-generated',
    'artificial intelligence generated',
    'machine learning generated',
    'midjourney',
    'dall-e',
    'stable diffusion'
  ],
  enabled: true,
  blockImages: true,
  blockText: true,
  confidence: 0.7,
  analyticsEnabled: true,
  licenseKey: null,
  licenseStatus: 'trial',
  licenseTrialStart: null,
  blockedDomains: [],
  whitelistedDomains: [],
  // How (if at all) to visually modify detected content.
  // 'none' = badge/flag only (no blur/hide/watermark)
  blockingMode: 'none', // none, blur, hide, watermark
  blockVideo: false,
  blockVideos: false,
  enableDeepfakeScan: false,
  // Crowd learning (OPT-IN): when enabled, the extension can
  // (a) upload privacy-safe feature votes only on explicit user feedback, and
  // (b) download signed heuristic deltas.
  crowdLearningEnabled: false,
  crowdLearningEndpoint: '',
  // Optional: hashed subfeature learning. Still privacy-safe (hashes only), but
  // increases cardinality and should be used conservatively.
  crowdLearningSubfeaturesEnabled: false,
  version: '2.0.0'
};

// Trial period: 30 days in milliseconds
const TRIAL_PERIOD = 30 * 24 * 60 * 60 * 1000;

// Analytics tracking
const analytics = {
  sessionStart: Date.now(),
  blocked: 0,
  analyzed: 0,
  domains: {},
  hourly: {},
  daily: {}
};

// Error logger
function logError(context, error) {
  console.error(`[AIB Error] ${context}:`, error);
  chrome.storage.local.get('errors', (data) => {
    const errors = data.errors || [];
    errors.push({
      timestamp: Date.now(),
      context,
      message: error?.message || String(error)
    });
    // Keep last 100 errors
    if (errors.length > 100) {
      errors.shift();
    }
    chrome.storage.local.set({ errors });
  });
}

// ============================================================================
// PRIVACY-SAFE CROWD LEARNING HELPERS
// ============================================================================

async function sha256Base64Url(input) {
  try {
    const data = (typeof input === 'string') ? new TextEncoder().encode(input) : input;
    const digest = await crypto.subtle.digest('SHA-256', data);
    const bytes = new Uint8Array(digest);
    let b64 = btoa(String.fromCharCode(...bytes));
    // base64url
    b64 = b64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
    return b64;
  } catch {
    return null;
  }
}

function getDayBucket(ts = Date.now()) {
  return Math.floor(ts / (24 * 60 * 60 * 1000));
}

// Rotating, non-unique cohort to help server-side rate limiting without identity.
async function getOrCreateDailyCohort(dayBucket) {
  return new Promise((resolve) => {
    chrome.storage.local.get(['aoCrowdCohortDay', 'aoCrowdCohort'], async (store) => {
      try {
        if (store.aoCrowdCohortDay === dayBucket && typeof store.aoCrowdCohort === 'number') {
          resolve(store.aoCrowdCohort);
          return;
        }
        const raw = new Uint32Array(1);
        crypto.getRandomValues(raw);
        const cohort = Number(raw[0] % 4096); // 0..4095
        chrome.storage.local.set({ aoCrowdCohortDay: dayBucket, aoCrowdCohort: cohort }, () => resolve(cohort));
      } catch {
        resolve(0);
      }
    });
  });
}

async function buildCrowdVotePacket(feedback) {
  // IMPORTANT: do not include URL, domain, raw content, or any stable ids.
  const day = getDayBucket(feedback?.ts || Date.now());
  const cohort = await getOrCreateDailyCohort(day);

  const rawFeatureIds = Array.isArray(feedback?.featureIds) ? feedback.featureIds : [];

  // Only allow schema-like IDs for network upload.
  const cleaned = rawFeatureIds
    .map(x => (typeof x === 'string' ? x.trim() : ''))
    .filter(Boolean)
    .filter(x => /^[a-zA-Z0-9:_\-\.]{1,140}$/.test(x));

  // Always upload node:* and any explicit deepfake/video feature IDs.
  const nodeOnly = cleaned.filter(x => x.startsWith('node:') || x.startsWith('df:') || x.startsWith('vid:'));

  // Optionally include hashed subfeatures (sf:*) when enabled.
  // Subfeatures MUST be hashed on-device into sf:<b64url> so the server never sees raw strings.
  // We only accept sf:* here if it appears already hashed.
  const subfeatures = cleaned.filter(x => x.startsWith('sf:'));

  const featureIds = [...new Set([...nodeOnly, ...subfeatures])].slice(0, 32);

  const vote = feedback?.label === 'confirm_ai' ? 'ai' : (feedback?.label === 'dismiss_not_ai' ? 'not_ai' : null);
  if (!vote) return null;

  // Optional: contentId is local-only; to avoid linkability, hash it with day.
  let cid = null;
  if (feedback?.contentId) {
    cid = await sha256Base64Url(`${day}:${String(feedback.contentId)}`);
  }

  return {
    v: 1,
    day,
    cohort,
    vote,
  // Feature IDs are schema-controlled strings (not user content)
    featureIds,
    // Confidence is coarse and optional (bucketed)
    conf: typeof feedback?.confidence === 'number' ? Math.round(feedback.confidence * 10) / 10 : null,
    cid,
  };
}

// Initialize extension
chrome.runtime.onInstalled.addListener((details) => {
  try {
    if (details.reason === 'install') {
      chrome.storage.sync.get(null, (items) => {
        try {
          if (Object.keys(items).length === 0) {
            const settings = {
              ...DEFAULT_SETTINGS,
              licenseTrialStart: Date.now()
            };
            chrome.storage.sync.set(settings);
          }
        } catch (e) {
          logError('Failed to initialize settings', e);
        }
      });
      // Show onboarding on next page visit, not immediately
      chrome.storage.local.set({ showOnboarding: true });
    } else if (details.reason === 'update') {
      migrateSettings();
    }
  } catch (e) {
    logError('Extension installation failed', e);
  }
});

// Periodic crowd model refresh (opt-in only)
try {
  chrome.alarms.create('aoCrowdModelRefresh', { periodInMinutes: 60 * 6 }); // every 6 hours
} catch {
  // ignore
}

chrome.alarms.onAlarm.addListener((alarm) => {
  if (alarm?.name === 'aoCrowdModelRefresh') {
    refreshCrowdModelIfEnabled();
  }
});

async function refreshCrowdModelIfEnabled() {
  return new Promise((resolve) => {
    chrome.storage.sync.get(['crowdLearningEnabled', 'crowdLearningEndpoint'], async (syncSettings) => {
      try {
        if (syncSettings?.crowdLearningEnabled !== true) return resolve(false);
        const endpoint = (syncSettings?.crowdLearningEndpoint || '').trim();
        if (!endpoint) return resolve(false);

        const url = `${endpoint.replace(/\/$/, '')}/v1/model`;
        const resp = await fetch(url, {
          method: 'GET',
          cache: 'no-store',
          credentials: 'omit',
          mode: 'cors',
          redirect: 'follow',
          referrerPolicy: 'no-referrer',
        });
        if (!resp.ok) return resolve(false);

        const model = await resp.json();

        const payload = {
          version: Number(model?.version) || 0,
          featureWeights: (model?.featureWeights && typeof model.featureWeights === 'object') ? model.featureWeights : {},
        };

        const signature = typeof model?.signature === 'string' ? model.signature : '';
        const alg = typeof model?.alg === 'string' ? model.alg : '';
        const kid = typeof model?.kid === 'string' ? model.kid : '';

        const verified = await verifyCrowdModelSignature(payload, signature, { alg, kid });

        // Only store/apply verified models.
        if (!verified) return resolve(false);

        // Anti-rollback: never accept a verified model older than what we already have.
        const current = await new Promise((r) => {
          chrome.storage.local.get(['aoCrowdModel'], (s) => r(s?.aoCrowdModel || null));
        });
        const currentVersion = Number(current?.version) || 0;
        if (payload.version && currentVersion && payload.version < currentVersion) {
          return resolve(false);
        }

        const safeModel = {
          ...payload,
          fetchedAt: Date.now(),
          verified: true,
          alg: alg || 'RS256',
          kid: kid || null,
        };

        chrome.storage.local.set({ aoCrowdModel: safeModel }, () => resolve(true));
      } catch (e) {
        logError('refreshCrowdModelIfEnabled failed', e);
        resolve(false);
      }
    });
  });
}

// Pinned RSA public key (PEM) used to verify server-signed models.
// Replace with your real public key (generated from the server private key).
const CROWD_MODEL_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
REPLACE_ME_WITH_YOUR_PUBLIC_KEY
-----END PUBLIC KEY-----`;

// Optional: bind verification to an expected key id (kid).
// If configured and the server returns a different kid, verification fails.
// This prevents downgrade/rotation attacks where an attacker serves a different
// signed model from an unexpected key.
const CROWD_MODEL_EXPECTED_KID = '';

// Store and compare the public-key fingerprint (TOFU pinning) to detect key swaps.
// This is a "gold nugget" defense: if a key ever changes, we fail closed.
// It helps even if a developer forgets to pin the exact PEM in builds.
async function sha256Hex(buf) {
  const digest = await crypto.subtle.digest('SHA-256', buf);
  const bytes = new Uint8Array(digest);
  return Array.from(bytes).map((b) => b.toString(16).padStart(2, '0')).join('');
}

function base64UrlToUint8Array(b64url) {
  const b64 = String(b64url || '').replace(/-/g, '+').replace(/_/g, '/');
  const padded = b64 + '==='.slice((b64.length + 3) % 4);
  const bin = atob(padded);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function makeCanonicalModelString(payload) {
  const version = Number(payload?.version) || 0;
  const fw = payload?.featureWeights && typeof payload.featureWeights === 'object' ? payload.featureWeights : {};
  const keys = Object.keys(fw).sort();
  const ordered = {};
  for (const k of keys) ordered[k] = fw[k];
  return JSON.stringify({ version, featureWeights: ordered });
}

async function importRsaPublicKey(pem) {
  const cleaned = pem
    .replace(/-----BEGIN PUBLIC KEY-----/g, '')
    .replace(/-----END PUBLIC KEY-----/g, '')
    .replace(/\s+/g, '');
  const der = Uint8Array.from(atob(cleaned), (c) => c.charCodeAt(0));
  return crypto.subtle.importKey(
    'spki',
    der,
    { name: 'RSASSA-PKCS1-v1_5', hash: 'SHA-256' },
    false,
    ['verify']
  );
}

async function verifyCrowdModelSignature(payload, signatureB64Url, meta = {}) {
  try {
    // Bind algorithm if provided.
    if (meta?.alg && meta.alg !== 'RS256') return false;
    // Bind key id if configured.
    if (CROWD_MODEL_EXPECTED_KID && meta?.kid && meta.kid !== CROWD_MODEL_EXPECTED_KID) return false;

    // Guard: don’t accept placeholder key.
    if (CROWD_MODEL_PUBLIC_KEY_PEM.includes('REPLACE_ME_WITH_YOUR_PUBLIC_KEY')) return false;
    if (!signatureB64Url) return false;

    // TOFU pinning: detect if the configured key changes over time.
    const cleaned = CROWD_MODEL_PUBLIC_KEY_PEM
      .replace(/-----BEGIN PUBLIC KEY-----/g, '')
      .replace(/-----END PUBLIC KEY-----/g, '')
      .replace(/\s+/g, '');
    const der = Uint8Array.from(atob(cleaned), (c) => c.charCodeAt(0));
    const fp = await sha256Hex(der);
    const pinnedOk = await new Promise((resolve) => {
      chrome.storage.local.get(['aoCrowdKeyFp'], (store) => {
        try {
          const prev = store?.aoCrowdKeyFp;
          if (!prev) {
            chrome.storage.local.set({ aoCrowdKeyFp: fp }, () => resolve(true));
            return;
          }
          resolve(prev === fp);
        } catch {
          resolve(false);
        }
      });
    });
    if (!pinnedOk) return false;

    const key = await importRsaPublicKey(CROWD_MODEL_PUBLIC_KEY_PEM);
    const msg = new TextEncoder().encode(makeCanonicalModelString(payload));
    const sig = base64UrlToUint8Array(signatureB64Url);
    return await crypto.subtle.verify({ name: 'RSASSA-PKCS1-v1_5' }, key, sig, msg);
  } catch {
    return false;
  }
}

// Migrate settings from old versions
function migrateSettings() {
  try {
    chrome.storage.sync.get(null, (items) => {
      try {
        const version = items.version || '1.0.0';
        if (version !== '2.0.0') {
          const updated = { 
            ...items, 
            ...DEFAULT_SETTINGS,
            version: '2.0.0',
            licenseTrialStart: items.licenseTrialStart || Date.now()
          };
          chrome.storage.sync.set(updated);
        }
      } catch (e) {
        logError('Settings migration failed', e);
      }
    });
  } catch (e) {
    logError('Migration initialization failed', e);
  }
}

// Listen for messages from content scripts and popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  try {
    if (!request || typeof request !== 'object') {
      sendResponse({ error: 'Invalid request' });
      return true;
    }

    // ---------------------------------------------------------------------
    // Compatibility shim: overlay popover uses submitCrowdVote
    // Map it onto the existing feedback pipeline (recordUserFeedback) so the
    // vote is stored locally and (if opt-in) uploaded to the crowd endpoint.
    // ---------------------------------------------------------------------
    if (request.action === 'submitCrowdVote') {
      try {
        const data = request?.payload || request?.data || {};
        // Re-dispatch internally so we keep one canonical implementation.
        request = { action: 'recordUserFeedback', data };
      } catch {
        sendResponse({ success: false, error: 'Invalid payload' });
        return true;
      }
    }

    if (request.action === 'getSettings') {
      chrome.storage.sync.get(null, (response) => {
        try {
          // Normalize settings keys across versions.
          // Historical inconsistency: some builds used blockVideos (plural) while
          // the content script expects blockVideo (singular).
          response = response || {};
          if (typeof response.blockVideo === 'undefined' && typeof response.blockVideos !== 'undefined') {
            response.blockVideo = response.blockVideos;
          }
          if (typeof response.blockVideos === 'undefined' && typeof response.blockVideo !== 'undefined') {
            response.blockVideos = response.blockVideo;
          }

          // Ensure new media toggles have safe defaults even if storage is old.
          if (typeof response.crowdLearningEnabled === 'undefined') response.crowdLearningEnabled = DEFAULT_SETTINGS.crowdLearningEnabled;
          if (typeof response.crowdLearningEndpoint === 'undefined') response.crowdLearningEndpoint = DEFAULT_SETTINGS.crowdLearningEndpoint;
          if (typeof response.blockVideo === 'undefined') response.blockVideo = DEFAULT_SETTINGS.blockVideo;
          if (typeof response.blockVideos === 'undefined') response.blockVideos = response.blockVideo;
          if (typeof response.blockAudio === 'undefined') response.blockAudio = true;
          if (typeof response.blockEmbeds === 'undefined') response.blockEmbeds = true;
          if (typeof response.blockDocuments === 'undefined') response.blockDocuments = true;
          if (typeof response.blockCanvas === 'undefined') response.blockCanvas = true;
          if (typeof response.goHard === 'undefined') response.goHard = false;

          // Check trial expiration
          if (response.licenseStatus === 'trial' && response.licenseTrialStart) {
            const trialExpired = (Date.now() - response.licenseTrialStart) > TRIAL_PERIOD;
            if (trialExpired) {
              response.licenseStatus = 'trial_expired';
            }
          }
          sendResponse(response || DEFAULT_SETTINGS);
        } catch (e) {
          logError('getSettings failed', e);
          sendResponse(DEFAULT_SETTINGS);
        }
      });
      return true;
    }

    if (request.action === 'getCrowdModel') {
      chrome.storage.local.get(['aoCrowdModel'], (store) => {
        try {
          sendResponse(store.aoCrowdModel || { version: 0, featureWeights: {}, verified: false });
        } catch (e) {
          logError('getCrowdModel failed', e);
          sendResponse({ version: 0, featureWeights: {}, verified: false });
        }
      });
      return true;
    }

    if (request.action === 'getCrowdSecurityStatus') {
      chrome.storage.local.get(['aoCrowdModel', 'aoCrowdKeyFp'], (store) => {
        try {
          const m = store?.aoCrowdModel || null;
          sendResponse({
            verified: !!m?.verified,
            version: Number(m?.version) || 0,
            fetchedAt: Number(m?.fetchedAt) || 0,
            alg: (typeof m?.alg === 'string' && m.alg) ? m.alg : null,
            kid: (typeof m?.kid === 'string' && m.kid) ? m.kid : null,
            keyFp: (typeof store?.aoCrowdKeyFp === 'string' && store.aoCrowdKeyFp) ? store.aoCrowdKeyFp : null,
          });
        } catch (e) {
          logError('getCrowdSecurityStatus failed', e);
          sendResponse({ verified: false, version: 0, fetchedAt: 0, alg: null, kid: null, keyFp: null });
        }
      });
      return true;
    }

    if (request.action === 'saveSettings') {
      if (!request.settings || typeof request.settings !== 'object') {
        sendResponse({ success: false, error: 'Invalid settings' });
        return true;
      }
      chrome.storage.sync.set(request.settings, () => {
        sendResponse({ success: true });
      });
      return true;
    }

    if (request.action === 'analyzeContent') {
      if (!request.content || !request.type) {
        sendResponse({ error: 'Missing required parameters' });
        return true;
      }
      analyzeContent(request.content, request.type, (result) => {
        sendResponse(result);
        if (request.url) {
          trackAnalytics(request.url, result, request.type);
        }
      });
      return true;
    }

    if (request.action === 'getAnalytics') {
      sendResponse(getAnalyticsReport());
      return true;
    }

    if (request.action === 'getLearningState') {
      chrome.storage.local.get(['aoDomainPriors'], (store) => {
        try {
          sendResponse({
            domainPriors: (store.aoDomainPriors && typeof store.aoDomainPriors === 'object') ? store.aoDomainPriors : {},
          });
        } catch (e) {
          logError('getLearningState failed', e);
          sendResponse({ domainPriors: {} });
        }
      });
      return true;
    }

    // Unified analytics events from content scripts (Agent Orange pipeline)
    if (request.action === 'trackAnalyticsEvent') {
      try {
        const url = request?.data?.url || sender?.url || '';
        const resultLike = {
          isAiGenerated: true,
          confidence: typeof request?.data?.confidence === 'number' ? request.data.confidence : 0
        };
        trackAnalytics(url, resultLike, request?.data?.type || 'unknown');
        sendResponse({ success: true });
      } catch (e) {
        logError('trackAnalyticsEvent failed', e);
        sendResponse({ success: false });
      }
      return true;
    }

    // Optional: accept periodic performance metrics from content scripts
    if (request.action === 'updateMetrics') {
      try {
        chrome.storage.local.set({ lastContentScriptMetrics: request.data, lastMetricsUpdate: Date.now() });
        sendResponse({ success: true });
      } catch (e) {
        logError('updateMetrics failed', e);
        sendResponse({ success: false });
      }
      return true;
    }

    // -----------------------------------------------------------------------
    // User feedback (local learning)
    // -----------------------------------------------------------------------
    if (request.action === 'recordUserFeedback') {
      try {
        const fb = request?.data;
        const label = fb?.label;
        if (!label) {
          sendResponse({ success: false, error: 'Missing label' });
          return true;
        }

        const url = fb?.url || sender?.url || '';
        let domain = '';
        try {
          domain = url ? (new URL(url)).hostname : '';
        } catch {
          domain = '';
        }

  chrome.storage.local.get(['aoFeedbackLog', 'aoDomainPriors'], (store) => {
          try {
            const log = Array.isArray(store.aoFeedbackLog) ? store.aoFeedbackLog : [];
            const priors = (store.aoDomainPriors && typeof store.aoDomainPriors === 'object') ? store.aoDomainPriors : {};

            // Keep a bounded local log for debugging/export (no network).
            log.push({
              ...fb,
              domain,
              ts: fb?.ts || Date.now(),
            });
            const MAX_LOG = 500;
            if (log.length > MAX_LOG) log.splice(0, log.length - MAX_LOG);

            // Simple online update for per-domain prior.
            // prior in [0,1] where 1 means "site tends to be AI".
            if (domain) {
              const prev = priors[domain] || { prior: 0.5, n: 0 };
              const y = label === 'confirm_ai' ? 1 : (label === 'dismiss_not_ai' ? 0 : null);
              if (y !== null) {
                const n = (prev.n || 0) + 1;
                const lr = 1 / Math.min(50, n); // diminishing learning rate
                const prior = clamp01((prev.prior ?? 0.5) * (1 - lr) + y * lr);
                priors[domain] = { prior, n, updatedAt: Date.now() };
              }
            }

            chrome.storage.local.set({
              aoFeedbackLog: log,
              aoDomainPriors: priors,
            }, () => sendResponse({ success: true, domain }));

            // Upload privacy-safe crowd vote ONLY if user opted in.
            chrome.storage.sync.get(['crowdLearningEnabled', 'crowdLearningEndpoint'], async (syncSettings) => {
              try {
                if (syncSettings?.crowdLearningEnabled !== true) return;
                const endpoint = (syncSettings?.crowdLearningEndpoint || '').trim();
                if (!endpoint) return;

                const packet = await buildCrowdVotePacket(fb);
                if (!packet) return;

                // Fire-and-forget. Do not include URL or any identity info.
                fetch(`${endpoint.replace(/\/$/, '')}/v1/vote`, {
                  method: 'POST',
                  headers: { 'content-type': 'application/json' },
                  body: JSON.stringify(packet),
                  cache: 'no-store',
                  credentials: 'omit',
                  mode: 'cors',
                  redirect: 'follow',
                  referrerPolicy: 'no-referrer',
                }).catch(() => { /* ignore */ });
              } catch {
                // ignore
              }
            });
          } catch (e) {
            logError('recordUserFeedback storage update failed', e);
            sendResponse({ success: false });
          }
        });
      } catch (e) {
        logError('recordUserFeedback failed', e);
        sendResponse({ success: false });
      }

      return true;
    }

    // -----------------------------------------------------------------------
    // Feature-level votes (from overlay popover)
    // - UI allows up/down per feature then "Apply"
    // - We store locally (debug) and optionally upload a privacy-safe packet
    //   by mapping the feature-level feedback to the existing /v1/vote schema.
    // -----------------------------------------------------------------------
    if (request.action === 'recordFeatureVotes') {
      try {
        const payload = request?.payload || {};
        const rawVotes = Array.isArray(payload?.featureVotes) ? payload.featureVotes : [];
        const cleanedFeatureIds = rawVotes
          .map(v => (typeof v?.featureId === 'string' ? v.featureId.trim() : ''))
          .filter(Boolean)
          .filter(x => /^[a-zA-Z0-9:_\-\.]{1,140}$/.test(x))
          .slice(0, 32);

        if (cleanedFeatureIds.length === 0) {
          sendResponse({ success: false, error: 'no_features' });
          return true;
        }

        // For now, we treat "Apply" as: user affirms these features are valid.
        // That corresponds to voting "ai" for the selected element.
        // (If we add feature polarity to server later, we can encode up/down.)
        const feedback = {
          ts: Date.now(),
          label: 'confirm_ai',
          confidence: typeof payload?.confidence === 'number' ? payload.confidence : null,
          featureIds: cleanedFeatureIds,
        };

        chrome.storage.local.get(['aoFeatureVoteLog'], (store) => {
          try {
            const log = Array.isArray(store.aoFeatureVoteLog) ? store.aoFeatureVoteLog : [];
            log.push({ ts: Date.now(), featureVotes: rawVotes, featureIds: cleanedFeatureIds });
            const MAX_LOG = 500;
            if (log.length > MAX_LOG) log.splice(0, log.length - MAX_LOG);
            chrome.storage.local.set({ aoFeatureVoteLog: log }, () => sendResponse({ success: true }));
          } catch (e) {
            logError('recordFeatureVotes storage failed', e);
            sendResponse({ success: false });
          }
        });

        // Optional crowd upload.
        chrome.storage.sync.get(['crowdLearningEnabled', 'crowdLearningEndpoint'], async (syncSettings) => {
          try {
            if (syncSettings?.crowdLearningEnabled !== true) return;
            const endpoint = (syncSettings?.crowdLearningEndpoint || '').trim();
            if (!endpoint) return;
            const packet = await buildCrowdVotePacket(feedback);
            if (!packet) return;
            fetch(`${endpoint.replace(/\/$/, '')}/v1/vote`, {
              method: 'POST',
              headers: { 'content-type': 'application/json' },
              body: JSON.stringify(packet),
              cache: 'no-store',
              credentials: 'omit',
              mode: 'cors',
              redirect: 'follow',
              referrerPolicy: 'no-referrer',
            }).catch(() => { /* ignore */ });
          } catch {
            // ignore
          }
        });

        return true;
      } catch (e) {
        logError('recordFeatureVotes failed', e);
        sendResponse({ success: false });
        return true;
      }
    }

    if (request.action === 'validateLicense') {
      if (!request.key) {
        sendResponse({ valid: false, message: 'No license key provided' });
        return true;
      }
      validateLicense(request.key, (result) => {
        sendResponse(result);
      });
      return true;
    }

    if (request.action === 'checkLicenseStatus') {
      chrome.storage.sync.get(['licenseStatus', 'licenseTrialStart'], (data) => {
        try {
          let status = data.licenseStatus || 'trial';
          // Check if trial expired
          if (status === 'trial' && data.licenseTrialStart) {
            const elapsed = Date.now() - data.licenseTrialStart;
            if (elapsed > TRIAL_PERIOD) {
              status = 'trial_expired';
              chrome.storage.sync.set({ licenseStatus: 'trial_expired' });
            }
          }
          sendResponse({ 
            status,
            daysRemaining: calculateTrialDaysRemaining(data.licenseTrialStart)
          });
        } catch (e) {
          logError('checkLicenseStatus failed', e);
          sendResponse({ status: 'trial', error: 'Failed to check status' });
        }
      });
      return true;
    }
  } catch (e) {
    logError('Message handler failed', e);
    sendResponse({ error: 'Internal error' });
  }

  return true;
});

function clamp01(x) {
  if (typeof x !== 'number' || Number.isNaN(x)) return 0;
  return Math.max(0, Math.min(1, x));
}

// Advanced content analysis
function analyzeContent(content, type = 'text', callback) {
  try {
    if (!content || typeof content !== 'string') {
      callback({ 
        isAiGenerated: false, 
        confidence: 0, 
        error: 'Invalid content'
      });
      return;
    }

    chrome.storage.sync.get(['blockedTerms', 'confidence'], (data) => {
      try {
        const blockedTerms = data.blockedTerms || DEFAULT_SETTINGS.blockedTerms;
        const confidence = data.confidence || DEFAULT_SETTINGS.confidence;
        
        if (!Array.isArray(blockedTerms)) {
          callback({ 
            isAiGenerated: false, 
            confidence: 0, 
            error: 'Invalid blocked terms configuration'
          });
          return;
        }

        const contentLower = content.toLowerCase().substring(0, 10000); // Limit size
        
        // Multiple scoring methods
        let keywordScore = calculateKeywordScore(contentLower, blockedTerms);
        let patternScore = calculatePatternScore(contentLower, type);
        let structureScore = calculateStructureScore(content, type);
        
        // Weighted combination
        const finalScore = (keywordScore * 0.4) + (patternScore * 0.35) + (structureScore * 0.25);
        
        const matchedTerms = blockedTerms.filter(term => 
          typeof term === 'string' && contentLower.includes(term.toLowerCase())
        );

        callback({
          isAiGenerated: finalScore > confidence,
          confidence: Math.min(Math.max(finalScore, 0), 1),
          matchedTerms,
          keywordScore: Math.min(Math.max(keywordScore, 0), 1),
          patternScore: Math.min(Math.max(patternScore, 0), 1),
          structureScore: Math.min(Math.max(structureScore, 0), 1),
          analysis: {
            type,
            timestamp: Date.now(),
            method: 'hybrid'
          }
        });
      } catch (e) {
        logError('Content analysis processing failed', e);
        callback({ 
          isAiGenerated: false, 
          confidence: 0, 
          error: 'Analysis failed'
        });
      }
    });
  } catch (e) {
    logError('analyzeContent initialization failed', e);
    callback({ 
      isAiGenerated: false, 
      confidence: 0, 
      error: 'Fatal error'
    });
  }
}

function calculateKeywordScore(content, terms) {
  try {
    let score = 0;
    const validTerms = Array.isArray(terms) ? terms.filter(t => typeof t === 'string') : [];
    
    validTerms.forEach(term => {
      if (content.includes(term.toLowerCase())) {
        score += 0.3;
      }
    });
    return Math.min(score, 1);
  } catch (e) {
    logError('Keyword score calculation failed', e);
    return 0;
  }
}

function calculatePatternScore(content, type) {
  try {
    let score = 0;
    
    // AI-related patterns
    const aiPatterns = [
      /\b(generated|created|made)\s+(by|with|using)\s+(ai|ml|neural|gpt)/gi,
      /\b(ai|artificial intelligence|machine learning)\s+(generated|created|made)\b/gi,
      /\b(powered by|using)\s+(openai|anthropic|stability|midjourney)/gi
    ];
    
    aiPatterns.forEach(pattern => {
      try {
        if (pattern.test(content)) {
          score += 0.3;
        }
      } catch (e) {
        // Skip invalid patterns
      }
    });
    
    return Math.min(score, 1);
  } catch (e) {
    logError('Pattern score calculation failed', e);
    return 0;
  }
}

function calculateStructureScore(content, type) {
  try {
    // Check linguistic and structural patterns
    let score = 0;
    
    if (type === 'text' && content && typeof content === 'string') {
      // Repetitive phrases common in AI output
      const sentences = content.match(/[^.!?]+[.!?]/g) || [];
      if (sentences.length > 3) {
        const firstWords = sentences.slice(0, 3).map(s => {
          const words = s.trim().split(/\s+/);
          return words.length > 0 ? words[0] : '';
        }).filter(w => w);
        if (firstWords.length > 1 && new Set(firstWords).size < 3) {
          score += 0.2; // Repetitive opening words
        }
      }
      
      // Check for overly formal language
      const formalWords = (content.match(/\b(furthermore|moreover|additionally|consequently)\b/gi) || []).length;
      if (formalWords > 2) {
        score += 0.15;
      }
    }
    
    return Math.min(score, 1);
  } catch (e) {
    logError('Structure score calculation failed', e);
    return 0;
  }
}

// Analytics tracking
function trackAnalytics(url, result, type) {
  try {
    if (!url || typeof url !== 'string') return;
    
    analytics.analyzed++;
    if (result && result.isAiGenerated) {
      analytics.blocked++;
    }
    
    // Track by domain
    try {
      const urlObj = new URL(url);
      const domain = urlObj.hostname;
      if (domain) {
        analytics.domains[domain] = (analytics.domains[domain] || 0) + 1;
      }
    } catch (e) {
      // Invalid URL, skip domain tracking
    }
    
    // Save analytics periodically (every 50 analyses)
    if (analytics.analyzed % 50 === 0) {
      saveAnalytics();
    }
  } catch (e) {
    logError('Analytics tracking failed', e);
  }
}

function saveAnalytics() {
  try {
    const timestamp = new Date().toISOString().split('T')[0];
    chrome.storage.local.set({
      [`analytics_${timestamp}`]: analytics,
      lastAnalyticsUpdate: Date.now()
    });
  } catch (e) {
    logError('Analytics save failed', e);
  }
}

function getAnalyticsReport() {
  try {
    const blockRate = analytics.analyzed > 0 
      ? ((analytics.blocked / analytics.analyzed) * 100).toFixed(2)
      : 0;
    
    return {
      totalAnalyzed: analytics.analyzed || 0,
      totalBlocked: analytics.blocked || 0,
      blockRate: `${blockRate}%`,
      sessionDuration: Date.now() - analytics.sessionStart,
      topDomains: Object.entries(analytics.domains || {})
        .sort(([, a], [, b]) => (b || 0) - (a || 0))
        .slice(0, 10)
        .map(([domain, count]) => ({ domain, count }))
    };
  } catch (e) {
    logError('Analytics report generation failed', e);
    return {
      totalAnalyzed: 0,
      totalBlocked: 0,
      blockRate: '0%',
      sessionDuration: 0,
      topDomains: [],
      error: 'Failed to generate report'
    };
  }
}

// License validation with trial period enforcement
function validateLicense(key, callback) {
  try {
    if (!key || typeof key !== 'string' || key.length < 10) {
      callback({ valid: false, message: 'Invalid license key format' });
      return;
    }
    
    // License format: AIB-XXXXXXXXXXXXXXXXXXXXXXXX (AIB- + 20 chars)
    const isValid = /^AIB-[A-Z0-9]{20}$/.test(key.toUpperCase());
    
    if (isValid) {
      chrome.storage.sync.set({ 
        licenseKey: key, 
        licenseStatus: 'active',
        licenseActivated: Date.now(),
        licenseExpiration: Date.now() + (365 * 24 * 60 * 60 * 1000) // 1 year
      }, () => {
        callback({ 
          valid: true, 
          message: 'License activated successfully',
          expirationDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString()
        });
      });
    } else {
      callback({ valid: false, message: 'License key not recognized' });
    }
  } catch (e) {
    logError('License validation failed', e);
    callback({ valid: false, message: 'Validation error occurred' });
  }
}

function calculateTrialDaysRemaining(trialStart) {
  try {
    if (!trialStart || typeof trialStart !== 'number') {
      return 30;
    }
    const elapsed = Date.now() - trialStart;
    const daysElapsed = Math.floor(elapsed / (24 * 60 * 60 * 1000));
    const daysRemaining = Math.max(0, 30 - daysElapsed);
    return daysRemaining;
  } catch (e) {
    return 30;
  }
}

// Context menu for quick actions
// Remove all existing context menus first to prevent duplicate ID errors
chrome.contextMenus.removeAll(() => {
  try {
    chrome.contextMenus.create({
      id: 'analyzeSelection',
      title: 'Analyze with AI Blocker',
      contexts: ['selection']
    }, () => {
      // Check for errors but don't crash if it already exists
      if (chrome.runtime.lastError) {
        console.warn('[Background] Context menu warning:', chrome.runtime.lastError.message);
      }
    });

    chrome.contextMenus.onClicked.addListener((info, tab) => {
      try {
        if (info.menuItemId === 'analyzeSelection') {
          const selectedText = info.selectionText;
          if (selectedText && typeof selectedText === 'string') {
            analyzeContent(selectedText, 'text', (result) => {
              if (tab && tab.id) {
                chrome.tabs.sendMessage(tab.id, {
                  action: 'showAnalysisResult',
                  result
                }).catch(() => {
                  // Tab may not be accessible
                });
              }
            });
          }
        }
      } catch (e) {
        logError('Context menu click handler failed', e);
      }
    });
  } catch (e) {
    logError('Failed to create context menu', e);
  }
});

// Performance optimization: Clean up old analytics data
try {
  chrome.alarms.create('cleanupAnalytics', { periodInMinutes: 1440 }); // Daily

  chrome.alarms.onAlarm.addListener((alarm) => {
    try {
      if (alarm && alarm.name === 'cleanupAnalytics') {
        chrome.storage.local.get(null, (items) => {
          try {
            const today = new Date().toISOString().split('T')[0];
            const keysToRemove = [];
            Object.keys(items || {}).forEach(key => {
              if (key.startsWith('analytics_') && !key.includes(today)) {
                const dateStr = key.replace('analytics_', '');
                const itemDate = new Date(dateStr);
                if (Date.now() - itemDate.getTime() > 30 * 24 * 60 * 60 * 1000) {
                  keysToRemove.push(key);
                }
              }
            });
            if (keysToRemove.length > 0) {
              chrome.storage.local.remove(keysToRemove);
            }
          } catch (e) {
            logError('Analytics cleanup processing failed', e);
          }
        });
      }
    } catch (e) {
      logError('Alarm handler failed', e);
    }
  });
} catch (e) {
  logError('Alarm creation failed', e);
}

