/*
 * Copyright (c) 2026 Ryan P. Walsh. All rights reserved.
 * Proprietary commercial software published for public reference only.
 */

// Weighted style-phrase lexicon (SpamAssassin-style, fully visible).
// Weights are log-odds of the phrase appearing in AI vs human text,
// measured on the tokenization-normalized HC3 tuning slice by
// test/fetch-bench.mjs + mining; topic words are excluded. Positive =
// AI-typical, negative = human-typical.
const SLOP_WEIGHTS = [
  ["important to remember", 2.84],
  ["it's also important", 2.25],
  ["also possible that", 3.06],
  ["important to note", 4.18],
  ["it's important to", 3.68],
  ["also important to", 2.59],
  ["to remember that", 2.81],
  ["a combination of", 1.88],
  ["because they are", 1.58],
  ["it is important", 4.05],
  ["is important to", 3.94],
  ["few reasons why", 3.46],
  ["hope this helps", 3.02],
  ["this means that", 2.94],
  ["this is because", 2.54],
  ["another reason", 3.6],
  ["reason is that", 3.09],
  ["which can make", 2.98],
  ["for example if", 2.9],
  ["there are many", 2.17],
  ["many different", 2.15],
  ["to ensure that", 1.6],
  ["have different", 1.45],
  ["however it is", 3.25],
  ["one reason is", 3.25],
  ["also known as", 3.09],
  ["a few reasons", 2.88],
  ["because it is", 2.36],
  ["important for", 1.99],
  ["difficult for", 1.95],
  ["to understand", 1.8],
  ["to note that", 4.17],
  ["while others", 3.28],
  ["a variety of", 3.11],
  ["you have any", 2.59],
  ["are designed", 2.25],
  ["is generally", 2.06],
  ["difficult to", 1.8],
  ["believe that", 1.6],
  ["overall the", 3.69],
  ["know if you", 3.16],
  ["can also be", 3.13],
  ["can help to", 3.13],
  ["can make it", 3.06],
  ["which means", 2.64],
  ["let me know", 2.5],
  ["i hope this", 2.33],
  ["some people", 1.92],
  ["there are a", 1.87],
  ["designed to", 1.85],
  ["this can be", 1.77],
  ["is possible", 1.52],
  ["possible to", 1.47],
  ["as a result", 1.47],
  ["are able to", 1.47],
  ["can lead to", 1.41],
  ["people may", 3.22],
  ["me know if", 3.16],
  ["it is also", 2.72],
  ["the use of", 2.29],
  ["that helps", 2.25],
  ["they might", 2.15],
  ["to protect", 1.98],
  ["that it is", 1.86],
  ["for people", 1.75],
  ["which is a", 1.6],
  ["if you are", 1.56],
  ["may not be", 1.47],
  ["a specific", 1.41],
  ["are a few", 3.19],
  ["and it is", 3.19],
  ["a type of", 2.98],
  ["can cause", 2.69],
  ["to try to", 2.59],
  ["are often", 2.39],
  ["a special", 1.96],
  ["also have", 1.88],
  ["it can be", 1.74],
  ["it is not", 1.7],
  ["might not", 1.67],
  ["over time", 1.57],
  ["to create", 1.47],
  ["helps to", 3.71],
  ["they may", 2.45],
  ["way that", 2.29],
  ["may have", 2.17],
  ["or other", 2.01],
  ["is often", 1.83],
  ["while it", 1.8],
  ["may also", 1.78],
  ["types of", 1.78],
  ["are used", 1.77],
  ["not have", 1.67],
  ["range of", 1.56],
  ["makes it", 1.55],
  ["that are", 1.52],
  ["going to", -1.48],
  ["such as", 2.08],
  ["and may", 2.03],
  ["to help", 1.88],
  ["is used", 1.7],
  ["be more", 1.56],
  ["be used", 1.54],
  ["made up", 1.47],
  ["and are", 1.43],
  ["in some", 1.42],
  ["and to", 1.66],
  ["may be", 1.65],
  ["do not", 1.56],
  ["when a", 1.54],
  ["and is", 1.52],
  ["or to", 2.43]
];

if (typeof module !== "undefined" && module.exports) module.exports = { SLOP_WEIGHTS };
